const std = @import("std");
const types = @import("../types.zig");
const symbol_table = @import("../symbol_table.zig");

// ============================================================================
// Plugin Interface
// Defines the contract that all plugins must implement
// ============================================================================

/// A synthetic call edge generated by a plugin
pub const SyntheticEdge = struct {
    /// FQN of the calling function/method (e.g., the dispatch site)
    caller_fqn: []const u8,

    /// FQN of the callee (e.g., the event handler method)
    callee_fqn: []const u8,

    /// File where the synthetic relationship originates
    file_path: []const u8,

    /// Line number of the dispatch/trigger site
    line: u32,

    /// Confidence score (0.0-1.0) for this edge
    /// - 1.0: Certain (exact event class match)
    /// - 0.85: High (external event class matched by FQCN)
    /// - 0.7: Medium (interface-based dispatch)
    /// - 0.5: Low (heuristic match)
    confidence: f32,

    /// Human-readable description of why this edge exists
    reason: []const u8,

    /// The originating plugin name
    plugin_name: []const u8,
};

/// Read-only context provided to plugins during analysis
pub const PluginContext = struct {
    allocator: std.mem.Allocator,
    sym_table: *const symbol_table.SymbolTable,

    /// All calls collected during analysis
    calls: []const types.EnhancedFunctionCall,

    /// All file sources indexed by file path (for re-parsing if needed)
    file_sources: *const std.StringHashMap([]const u8),

    /// Project configurations (multiple for monorepo mode)
    project_configs: []const types.ProjectConfig,

    /// Helper to look up a class by FQCN
    pub fn getClass(self: *const PluginContext, fqcn: []const u8) ?*const types.ClassSymbol {
        return self.sym_table.getClass(fqcn);
    }

    /// Helper to get all classes implementing an interface
    pub fn getImplementors(self: *const PluginContext, interface_fqcn: []const u8) ![]const types.ClassSymbol {
        var result: std.ArrayListUnmanaged(types.ClassSymbol) = .empty;

        var it = self.sym_table.classes.valueIterator();
        while (it.next()) |class| {
            for (class.implements) |iface| {
                if (std.mem.eql(u8, iface, interface_fqcn)) {
                    try result.append(self.allocator, class.*);
                    break;
                }
            }
        }

        return result.toOwnedSlice(self.allocator);
    }

    /// Helper to find all calls to a specific method pattern
    /// class_pattern: if null, matches any class; otherwise matches class name (can be partial)
    /// method_name: exact method name to match
    pub fn findCallsTo(
        self: *const PluginContext,
        class_pattern: ?[]const u8,
        method_name: []const u8,
    ) ![]const types.EnhancedFunctionCall {
        var result: std.ArrayListUnmanaged(types.EnhancedFunctionCall) = .empty;

        for (self.calls) |call| {
            if (!std.mem.eql(u8, call.callee_name, method_name)) continue;

            if (class_pattern) |pattern| {
                if (call.resolved_target) |target| {
                    // Check if target contains the pattern
                    if (std.mem.indexOf(u8, target, pattern) != null) {
                        try result.append(self.allocator, call);
                    }
                }
            } else {
                // No class pattern - match any
                try result.append(self.allocator, call);
            }
        }

        return result.toOwnedSlice(self.allocator);
    }

    /// Helper to find all calls within a specific function/method
    pub fn findCallsFrom(
        self: *const PluginContext,
        caller_fqn: []const u8,
    ) ![]const types.EnhancedFunctionCall {
        var result: std.ArrayListUnmanaged(types.EnhancedFunctionCall) = .empty;

        for (self.calls) |call| {
            if (std.mem.eql(u8, call.caller_fqn, caller_fqn)) {
                try result.append(self.allocator, call);
            }
        }

        return result.toOwnedSlice(self.allocator);
    }
};

/// Plugin interface that all plugins must implement
pub const Plugin = struct {
    /// Plugin name for identification and CLI flags
    name: []const u8,

    /// Human-readable description
    description: []const u8,

    /// Version string
    version: []const u8,

    /// The analyze function pointer
    analyzeFn: *const fn (ctx: *const PluginContext) anyerror![]const SyntheticEdge,

    /// Perform analysis and return synthetic edges
    pub fn analyze(self: *const Plugin, ctx: *const PluginContext) ![]const SyntheticEdge {
        return self.analyzeFn(ctx);
    }
};

// ============================================================================
// Tests
// ============================================================================

test "SyntheticEdge creation" {
    const edge = SyntheticEdge{
        .caller_fqn = "Test\\Service::dispatch",
        .callee_fqn = "Test\\Subscriber::onEvent",
        .file_path = "/test/Service.php",
        .line = 42,
        .confidence = 0.95,
        .reason = "Symfony event dispatch",
        .plugin_name = "symfony-events",
    };

    try std.testing.expectEqualStrings("Test\\Service::dispatch", edge.caller_fqn);
    try std.testing.expectEqual(@as(f32, 0.95), edge.confidence);
}
